spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/school_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
  flyway:
    url: jdbc:postgresql://localhost:5432/school_db
    user: postgres
    password: 1234
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
    enabled: true