spring:
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:5432/school_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
  flyway:
    baseline-on-migrate: true